version: "3.9"

services:
  model:
    gpus: all
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-node
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false       # カーネルのネットワークスタックを使う
      - TS_HOSTNAME=docker-ts-node # ホスト名設定
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale-state:/var/lib/tailscale
    restart: unless-stopped # 手動停止の場合を除き，停止時には自動再起動を試みる

  machine-ubuntu:
    build: ./machine
    container_name: machine-node
    network_mode: service:tailscale
    depends_on:
      - tailscale
    # deploy:
    #   resources:
    #     # GPUデバイスの予約設定
    #     reservations:
    #       devices:
    #          # NVIDIAドライバを使用するデバイスの設定
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
volumes:
  tailscale-state:
